# create a dev conda environment with: `make create_env` or `conda env create -f environment.yml`
name: amelio_cp
channels:
- conda-forge # downaload packages from conda-forge (instead of pip)
- defaults
dependencies:
- python=3.13
- numpy=2.2.6
- pandas
- scikit-learn=1.7.2
- scipy
- scikit-optimize
- shap=0.46.0
- joblib
- bayesian-optimization